version: 2
defaults: &defaults
  docker:
    - image: circleci/python:3.8


jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore-cache:
          key: deps-{{ checksum "requirements.txt" }}

      - run:
          name: Install requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Run linters
          command: |
            . venv/bin/activate
            make lint
      - run:
          name: Test
          command: |
            . venv/bin/activate
            make test

      - persist_to_workspace:
          root: .
          paths:
            - ".git"
            - "venv"
            - ".circleci"

workflows:
  version: 2
  continuous-delivery:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
